name: mediremind
description: A medical appointment reminder application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  intl: ^0.18.1
  flutter_datetime_picker_plus: ^1.5.0
  flutter_secure_storage: ^9.0.0
  badges: ^3.1.2
  flutter_svg: ^2.0.7
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 